/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pimp-of-pimps' at '3/15/18 2:00 PM' with Gradle 2.10
 *
 * @author pimp-of-pimps, @date 3/15/18 2:00 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
