
/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'pimp-of-pimps' at '3/15/18 2:00 PM' with Gradle 2.10
 *
 * @author pimp-of-pimps, @date 3/15/18 2:00 PM
 */
public class LibraryTest {
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
    }
}
